language: python

install:
  - pip install -r requirements.txt

script:
  - tox

env:
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=memorytest27
  - TOXENV=memorytest34
  - TOXENV=doctest27
