language: python
sudo: false
install:
  - pip install -r requirements.txt

python:
  - 3.5

script:
  - tox

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=pypy-5.7.1
  - TOXENV=memorytest27
  - TOXENV=memorytest36
  - TOXENV=doctest27
  - TOXENV=coverage-py36
