language: python

install:
  - pip install -r requirements.txt

script:
  - tox

env:
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=memorytest27
  - TOXENV=memorytest32
  - TOXENV=doctest27
  - TOXENV=doctest32
